/**
 * Map Nutrition5k ingredient names to Pureat's coarse food categories.
 *
 * Strategy: keyword heuristics + exact overrides. Condiments, oils, spices,
 * and small garnishes are intentionally left unmapped so they do not skew
 * the weight distribution of real food categories.
 */

export const CATEGORIES = [
  "poultry",
  "beef",
  "pork",
  "fish",
  "seafood",
  "rice",
  "pasta",
  "potato",
  "bread",
  "salad",
  "vegetable",
  "fruit",
  "dessert",
  "beverage",
  "egg",
  "soup",
  "mixed_dish",
] as const;

export type Category = (typeof CATEGORIES)[number];

export const CATEGORY_KEYWORDS: Record<Category, string[]> = {
  poultry: [
    "chicken",
    "turkey",
    "duck",
    "hen",
    "drumstick",
    "chicken apple sausage",
    "chicken sausage",
  ],
  beef: [
    "beef",
    "steak",
    "hamburger",
    "burger patty",
    "meatball",
    " brisket",
    "roast beef",
    "ground beef",
    "beef patty",
  ],
  pork: [
    "pork",
    "bacon",
    "ham",
    "sausage",
    "bratwurst",
    "hot dog",
    "pepperoni",
    "salami",
    "prosciutto",
    "chorizo",
    "andouille",
  ],
  fish: [
    "salmon",
    "cod",
    "tuna",
    "tilapia",
    "catfish",
    "trout",
    "mahi",
    "halibut",
    "sardine",
    "anchovy",
    "fish",
    "fish cake",
  ],
  seafood: [
    "shrimp",
    "prawn",
    "scallop",
    "crab",
    "lobster",
    "clam",
    "mussel",
    "oyster",
    "squid",
    "octopus",
    "crawfish",
    "crayfish",
  ],
  rice: [
    "rice",
    "risotto",
    "pilaf",
    "fried rice",
    "white rice",
    "brown rice",
    "jasmine rice",
    "basmati rice",
    "wild rice",
    "millet",
    "quinoa",
    "farro",
    "barley",
    "couscous",
    "bulgur",
  ],
  pasta: [
    "pasta",
    "spaghetti",
    "noodle",
    "macaroni",
    "penne",
    "fettuccine",
    "linguine",
    "rigatoni",
    "orzo",
    "ramen",
    "udon",
    "soba",
    "lo mein",
    "chow mein",
    "pad thai",
  ],
  potato: [
    "potato",
    "fries",
    "french fries",
    "baked potato",
    "mashed potato",
    "hash brown",
    "tater tot",
    "sweet potato",
    "yam",
  ],
  bread: [
    "bread",
    "toast",
    "bun",
    "bagel",
    "croissant",
    "roll",
    "pita",
    "naan",
    "tortilla",
    "flatbread",
    "biscuit",
    "muffin",
    "sourdough",
    "multigrain bread",
    "rye bread",
    "wheat bread",
  ],
  salad: [
    "salad",
    "mixed greens",
    "green salad",
    "caesar salad",
    "garden salad",
    "spinach salad",
  ],
  vegetable: [
    "broccoli",
    "carrot",
    "green beans",
    "vegetable",
    "spinach",
    "mushroom",
    "onion",
    "garlic",
    "pepper",
    "tomato",
    "lettuce",
    "cabbage",
    "cauliflower",
    "brussels sprout",
    "asparagus",
    "zucchini",
    "squash",
    "cucumber",
    "celery",
    "kale",
    "chard",
    "bok choy",
    "napa cabbage",
    "edamame",
    "peas",
    "corn",
    "beet",
    "radish",
    "turnip",
    "parsnip",
    "rutabaga",
    "artichoke",
    "eggplant",
    "okra",
    "leek",
    "shallot",
    "scallion",
    "chive",
    "jalapeno",
    "jalape",
    "habanero",
    "chili",
    "chile",
    "cilantro",
    "parsley",
    "basil",
    "mint",
    "dill",
    "thyme",
    "rosemary",
    "oregano",
    "sage",
    "kale",
    "arugula",
    "watercress",
    "endive",
    "radicchio",
    "escarole",
    "bamboo shoot",
    "water chestnut",
    "bean sprout",
    "sprout",
  ],
  fruit: [
    "apple",
    "banana",
    "berry",
    "berries",
    "strawberry",
    "strawberries",
    "blueberry",
    "blueberries",
    "raspberry",
    "raspberries",
    "blackberry",
    "blackberries",
    "grape",
    "grapes",
    "orange",
    "lemon",
    "lime",
    "pineapple",
    "mango",
    "peach",
    "pear",
    "plum",
    "cherry",
    "melon",
    "watermelon",
    "cantaloupe",
    "honeydew",
    "kiwi",
    "papaya",
    "guava",
    "passion fruit",
    "pomegranate",
    "fig",
    "date",
    "raisin",
    "cranberry",
    "cranberries",
    "plantain",
    "avocado",
    "coconut",
  ],
  dessert: [
    "cake",
    "ice cream",
    "cookie",
    "chocolate",
    "dessert",
    "brownie",
    "pie",
    "tart",
    "pastry",
    "donut",
    "muffin",
    "cupcake",
    "pudding",
    "custard",
    "mousse",
    "cheesecake",
    "cobbler",
    "crisp",
    "sorbet",
    "gelato",
    "granola bar",
    "energy bar",
  ],
  beverage: [
    "soda",
    "soft drink",
    "juice",
    "milk",
    "coffee",
    "tea",
    "drink",
    "smoothie",
    "shake",
    "lemonade",
    "water",
  ],
  egg: [
    "egg",
    "omelette",
    "omelet",
    "scrambled egg",
    "fried egg",
    "boiled egg",
    "poached egg",
    "egg white",
    "egg yolk",
    "frittata",
    "quiche",
  ],
  soup: [
    "soup",
    "stew",
    "curry",
    "chowder",
    "broth",
    "bisque",
    "gumbo",
    "pho",
    "ramen",
    "minestrone",
    "lentil soup",
    "tomato soup",
    "vegetable soup",
    "chicken soup",
  ],
  mixed_dish: [
    "pizza",
    "burger",
    "sandwich",
    "taco",
    "burrito",
    "hotdog",
    "quesadilla",
    "enchilada",
    "empanada",
    "wrap",
    "pita pocket",
    "sushi",
    "sashimi",
    "poke",
    "bowl",
    "hummus",
    "salsa",
    "guacamole",
    "tabbouleh",
    "lasagna",
    "casserole",
    "gratin",
    "stir fry",
    "stir-fry",
    "paella",
    "jambalaya",
    "bibimbap",
    "dumpling",
    "spring roll",
    "egg roll",
    "samosa",
    "calzone",
    "stromboli",
    "pierogi",
    "gnocchi",
    "ravioli",
    "tortellini",
    "manicotti",
    "cannelloni",
    "meatloaf",
    "kebab",
    "skewer",
    "satay",
    "tofu",
    "seitan",
    "tempeh",
    "veggie burger",
    "granola",
    "muesli",
  ],
};

/**
 * Exact overrides for ambiguous or multi-word ingredient names.
 * These take precedence over keyword matching.
 */
export const CATEGORY_OVERRIDES: Record<string, Category> = {
  // grains / starches
  "white rice": "rice",
  "brown rice": "rice",
  "fried rice": "rice",
  "wild rice": "rice",
  "jasmine rice": "rice",
  "basmati rice": "rice",
  "multigrain bread": "bread",
  "sourdough bread": "bread",
  "rye bread": "bread",
  "wheat bread": "bread",
  "whole wheat bread": "bread",
  "hash browns": "potato",
  "tater tots": "potato",
  "sweet potato": "potato",

  // proteins
  "chicken apple sausage": "poultry",
  "chicken sausage": "poultry",
  "ground beef": "beef",
  "roast beef": "beef",
  "beef patty": "beef",
  "hot dog": "pork",
  "scrambled eggs": "egg",
  "egg whites": "egg",
  "fried egg": "egg",

  // vegetables / fruits / ambiguous
  "mixed greens": "salad",
  "green salad": "salad",
  "caesar salad": "salad",
  "spinach salad": "salad",
  "bok choy": "vegetable",
  "edamame": "vegetable",
  "plantain": "fruit",
  "avocado": "fruit",

  // mixed / prepared
  "chicken nuggets": "mixed_dish",
  hummus: "mixed_dish",
  salsa: "mixed_dish",
  guacamole: "mixed_dish",
  "spring roll": "mixed_dish",
  "egg roll": "mixed_dish",
  tofu: "mixed_dish",
  oatmeal: "mixed_dish",
  granola: "mixed_dish",
  croutons: "bread",
  almonds: "mixed_dish",
  walnuts: "mixed_dish",
  nuts: "mixed_dish",
  wine: "beverage",
  "white wine": "beverage",
};

/**
 * Ingredient names that should never be mapped to a category because they are
 * condiments, oils, spices, or garnishes used in small quantities.
 */
const EXCLUDED_INGREDIENTS = new Set([
  "soy sauce",
  "vinegar",
  "olive oil",
  "vegetable oil",
  "canola oil",
  "sesame oil",
  "coconut oil",
  "salt",
  "sugar",
  "brown sugar",
  "powdered sugar",
  "honey",
  "syrup",
  "maple syrup",
  "lemon juice",
  "lime juice",
  "vinaigrette",
  "dressing",
  "mayonnaise",
  "mustard",
  "ketchup",
  "hot sauce",
  "sriracha",
  "worcestershire sauce",
  "fish sauce",
  "oyster sauce",
  "hoisin sauce",
  "teriyaki sauce",
  "bbq sauce",
  "barbecue sauce",
  "marinara sauce",
  "tomato sauce",
  "pasta sauce",
  "alfredo sauce",
  "soy milk",
  "almond milk",
  "oat milk",
  "milk",
  "cream",
  "butter",
  "margarine",
  "cheese",
  "parmesan",
  "mozzarella",
  "cheddar",
  "feta",
  "goat cheese",
  "cream cheese",
  "ricotta",
  "yogurt",
  "sour cream",
  "water",
  "ice",
]);

export function normalizeIngredientName(name: string): string {
  return name
    .toLowerCase()
    .replace(/\s+/g, " ")
    .trim();
}

export function mapIngredientToCategory(
  name: string
): Category | "excluded" | undefined {
  const normalized = normalizeIngredientName(name);

  if (EXCLUDED_INGREDIENTS.has(normalized)) {
    return "excluded";
  }

  const override = CATEGORY_OVERRIDES[normalized];
  if (override) {
    return override;
  }

  const keywords = Object.entries(CATEGORY_KEYWORDS).flatMap(
    ([category, words]) => words.map((word) => ({ category, word }))
  );

  // Prefer longer keywords so "chicken breast" beats "chicken".
  keywords.sort((a, b) => b.word.length - a.word.length);

  for (const { category, word } of keywords) {
    if (normalized.includes(word.toLowerCase())) {
      return category as Category;
    }
  }

  return undefined;
}
